# Generated by Django 3.0.8 on 2020-07-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_auto_20200707_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_status', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
