# Generated by Django 3.0.8 on 2020-07-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_auto_20200724_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='power_status',
        ),
    ]
